config/routes.rb
Rails.application.routes.draw do
   devise_for :users, skip: [:registrations]
   as :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      get 'dashboard' => 'devise/sessions#new'
  end
  resources :users, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :surgeons
  resources :locations do
    resources :surgeons
  end
  resources :searches
  resources :admin_analytics
  # root 'surgeons#index'

  # routes to set location/surgeon to "live/public"
  get 'set_surgeon_status', to: 'surgeons#set_status'
  get 'set_location_status', to: 'locations#set_status'
  # root page
  root 'admin_analytics#dashboard'

  # surgeon locator page - internal
  get 'search_surgeons', to: 'searches#surgeon_locator'
  #display the surgeons when details are submitted in surgeon locator page
  post '/map_the_surgeons',  to: 'searches#map_the_surgeons'

  #track the website click in surgeon locator page
  get '/track_the_clicks', to: 'searches#track_the_clicks'

  #export db as .xls for admin
  get '/export_db', to: 'admin_analytics#export_db'

  #admin analytics - search results
  get '/search_results', to: 'admin_analytics#search_results'
  #admin analytics - download pdf report for surgeon
  get 'generate_report', to: 'admin_analytics#generate_report'
  #admin analytics - show heat map in pdfs
  get '/show_heat_map', to: 'admin_analytics#show_heat_map'
  #admin analytics - download client reports
  get '/client_reports', to: 'admin_analytics#client_reports'

  #list of all users - admin/location manager
  get '/users', to: 'admin_analytics#users_list'
  get '/reactive_users', to: 'admin_analytics#reactive_users'
  get 'update_reactive_user/:id', controller: 'admin_analytics', action: :update_reactive_user, as: :update_reactive_user

  #track the phone number clicks in surgeon locator page
   post '/track_the_phone', to: 'searches#track_the_phone'

  #external - surgeon locator
  get 'surgeon_finder', to: 'searches#surgeon_finder'
  get 'dashboard', to: 'admin_analytics#dashboard'

  #activate surgeons/locations
  get 'activate_surgeons', to: 'admin_analytics#activate_surgeons'
  get 'publish_surgeon', to: 'admin_analytics#publish_surgeon'
  get 'activate_locations', to: 'admin_analytics#activate_locations'
  get 'publish_location', to: 'admin_analytics#publish_location'
end

app/models/surgeon.rb
class Surgeon < ApplicationRecord
  belongs_to :location
  has_many :search_results, dependent: :destroy
  has_many :links, dependent: :destroy

  #serialize :proc_types
  
  validates_presence_of :full_name
  STATUS = %w[private publish]
  
  before_save do 
    self.procedure_types_array.reject! { |c| c.to_s == "0" }
  end
  
  def self.search(search)
    surgeons = all # for not existing search params
    surgeons = surgeons.where("LOWER(full_name) like LOWER('%#{search}%') OR LOWER(email) like LOWER('%#{search}%') OR LOWER(url) like LOWER('%#{search}%')") if search
    surgeons
  end
  
  def self.search_by_location(search, location_id)
    surgeons = all.where("location_id = ?", location_id) #surgeons for a particular location
    surgeons = surgeons.where("location_id = #{location_id} AND (LOWER(full_name) like LOWER('%#{search}%') OR LOWER(email) like LOWER('%#{search}%') OR LOWER(url) like LOWER('%#{search}%')) ") if search #surgeons for a particular location when searched for
    surgeons
  end

end

app/controllers/surgeons_controller.rb
class SurgeonsController < ApplicationController
  def index
    if params[:location_id]
      @location = Location.find(params[:location_id])
      @surgeons = Surgeon.search_by_location(params[:search], @location.id).paginate(:page => params[:page], :per_page => 30)
    elsif params[:user_id]
      #show surgeons for a location
      @location = Location.find_by_user_id(params[:user_id])
      @surgeons = Surgeon.search_by_location(params[:search], @location.id).paginate(:page => params[:page], :per_page => 30) if @location
    else
      if current_user && current_user.admin?
        @surgeons = Surgeon.search(params[:search]).paginate(:page => params[:page], :per_page => 30) #show all surgeons
      elsif current_user && current_user.manager?
        @location = Location.find_by_user_id(current_user.id)
        @surgeons = Surgeon.search_by_location(params[:search], @location.id).paginate(:page => params[:page], :per_page => 30) if @location
      end
    end
  end

  def new
    @location = Location.find(params[:location_id])
    @surgeon = @location.surgeons.new
    # params[:url] = @location.website
    # params[:phone] = @location.phone_number
  end

  def create
    @surgeon = Surgeon.new(params_surgeon)
    #    @surgeon.status = "publish" if current_user && current_user.admin?
    if @surgeon.save
      if current_user && current_user.manager?
        @admins = User.where("role = ? and deleted_at is NULL", "admin")
        @admins.each do |admin|
          NotificationMailer.added_surgeons_email(@surgeon, admin.email).deliver_now
        end
        flash[:notice] = "Surgeon has been successfully created. Admin will verify and approve the surgeon."
        redirect_to surgeons_path(:user_id => current_user.id)
      elsif current_user && current_user.admin?
        flash[:notice] = "Surgeon has been successfully created."
        redirect_to surgeons_path
      end
    else
      render "new"
    end
  end

  def show
    @surgeon = Surgeon.find(params[:id])
    @location = Location.find(@surgeon.location_id)
  end

  def edit
    @surgeon = Surgeon.find(params[:id])
    @location = Location.find(@surgeon.location_id)
  end

  def update
    @surgeon = Surgeon.find(params[:id])
    @location = Location.find(@surgeon.location_id)
    if @surgeon.update(params_surgeon)
      flash[:notice] = "Surgeon has been successfully updated."
      redirect_to surgeons_path
    else
      render "edit"
    end
  end

  def destroy
    @surgeon = Surgeon.find(params[:id])
    @surgeon.destroy
    flash[:notice] = "Surgeon has been successfully deleted."
    redirect_to surgeons_path
  end

  #make the surgeon status from private to publish
  #  def set_status
  #    if current_user && current_user.admin?
  #      @surgeon = Surgeon.find(params[:id])
  #      @surgeon.update_column(:status, "publish")
  #      flash[:notice] = "Surgeon has been successfully made live."
  #    else
  #      flash[:notice] = "Sorry. Only admin has the rights to make a surgeon live."
  #    end
  #    redirect_to surgeons_path
  #  end

  private

  def params_surgeon
    params.require(:surgeon).permit(:location_id, :full_name, :email, :suffix, :url, :phone, :status, :procedure_types_array => [])
  end
end

app/helpers/surgeons_helper.rb
module SurgeonsHelper
  
  def get_procedure_types
    ['Comprehensive Care Cervical', 'Comprehensive Care Lumbar', 'Cervical Fusion', 'Lumbar Fusion', 'Cervical Motion', 'Lumbar Motion']
  end
  
  def get_areas_of_discomfort
    ['Cervical (Neck, Shoulders & Arms)', 'Lumbar (Lower Back & Legs)']
  end
  
end

app/views/surgeons/_form.html.erb
<%= form_with model: @surgeon, local: true, :class => 'w-full max-w-lg' do |f| %>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<div class="">
    <% if @surgeon.errors.any? %>
    <div id="error_explanation" style="color: red">
        <h2><% @count = @surgeon.errors.count %>
            <%= pluralize(@count, "error") %>prohibited
            this surgeon from being saved:</h2>
        <ul>
            <% @surgeon.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :location, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
        <%= f.select :location_id, options_for_select([['Select Location', '']]+Location.all.map{|location| [location.address, location.id]}, @surgeon.location_id), {}, autofocus: true, :class => "block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
</div>

<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :full_name, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :full_name, autofocus: true, required: true, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :email, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.email_field :email, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :website_url, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <% if !@surgeon.url %><% @website = @location.website %><% elsif @surgeon.url %><% @website = @surgeon.url %><% else %><% @website = "" %><% end %>
        <%= f.text_field :url, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500", value: @website %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :phone_no, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <% if !@surgeon.phone %><% @phone = @location.phone_number %><% elsif @surgeon.phone %><% @phone = @surgeon.phone %><% else %><% @phone = "" %><% end %>
        <%= f.text_field :phone, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500", value: @phone %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :professional_suffix, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :suffix, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<% if current_user && current_user.admin? %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :status, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.collection_select :status, Surgeon::STATUS, :to_s, :titleize, {selected: @surgeon.status}, {class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"} %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.label "Set procedure types by checking the below boxes",:class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
</div>
<br/>
<% @surgeon_proc = @surgeon.procedure_types_array %> 


<% @proc = get_procedure_types %>
<% @proc.each do |proc_type| %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
            <%= proc_type %>
        </label>
        <br/>
    </div>
    <div class="md:w-2/3"> 

    	<% if @surgeon_proc && @surgeon_proc.include?(proc_type.to_s)%>
			<%= f.check_box :procedure_types_array, {multiple: true, checked: true}, proc_type %>
		<% else %>
			<%= f.check_box :procedure_types_array, {multiple: true}, proc_type %>
		<% end %>
        
    </div>
</div>
<% end %>
<% end %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <% if params[:location_id] %>
        <%= f.hidden_field :location_id, value: params[:location_id] %>
        <% end %>
    </div>
    <div class="md:w-2/3">
        <% if params[:location_id] %>
        <%= f.submit 'Save Surgeon', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <% else %>
        <%= f.submit 'Update', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <% end %>
    </div>
</div>
<% end %>

app/views/surgeons/edit.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Edit Surgeon</h3>
</div>

<div class="flex flex-wrap">
	<%= render 'form' %>
</div>

app/views/surgeons/index.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">All Surgeons - Listing of all the surgeons 
	<% if @location && params[:user_id] %> in my location: 
		<% if @location.name && @location.name != "" %><%= @location.name %><% end %>
		<% if @location.address_1 && @location.address_1 != "" %>, <%= @location.address_1 %><% end %>
		<% if @location.address_2 && @location.address_2 != "" %>, <%= @location.address_2 %><% end %>
		<% if @location.city && @location.city != "" %>, <%= @location.city %><% end %>
		<% if @location.state && @location.state != "" %>, <%= @location.state %><% end %>
		<% if @location.zip && @location.zip != "" %>-<%= @location.zip %><% end %>
	<% else %>the system
	<% end %>
	</h3>
</div>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= form_tag surgeons_path, method: :get do %>
  <% if params[:search] && params[:search] != "" %>
  	<% @search_val = params[:search] %>
  <% else %>
  	<% @search_val = "" %>
  <% end %>
  <%= text_field_tag :search, @search_val, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
  <% if params[:user_id] && params[:user_id] != "" %>
  <%= hidden_field_tag :user_id, params[:user_id] %>
  <% end %>
  <%= submit_tag "Search", :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
<% end %>
<% if @surgeons && @surgeons.length > 0 %>
	<table class="table-fixed">
		<thead>
		<tr>
			<th class="px-4 py-2">First Name</th>
			<th class="px-4 py-2">Last Name</th>
			<th class="px-4 py-2">Email</th>
			<th class="px-4 py-2">Website Url</th>
			<th class="px-4 py-2">Location</th>
			<th class="px-4 py-2">Status</th>
			<th class="px-4 py-2"></th>
			
		</tr>
		</thead>
		<tbody>
			<% status_mapping = { "publish" => "Published", "private" => "Private" } %>
			<% @surgeons.each do |surgeon| %>
				<tr>
					<td class="border px-4 py-2">
						<%= surgeon.full_name.to_s.split(" ").first %>
					</td>
					<td class="border px-4 py-2">
						<% if surgeon.suffix && surgeon.suffix != "" %>
							<%= surgeon.full_name.to_s.split(" ").last %>, <%= surgeon.suffix %>
						<% else %>
							<%= surgeon.full_name.to_s.split(" ").last %>
						<% end %>
					</td>
					<td class="border px-4 py-2"><%= surgeon.email %></td>
					<td class="border px-4 py-2" style="max-width:250px;word-wrap:break-word;"><%= surgeon.url %></td>
					<% surgeon_location = surgeon.location %>
					<td class="border px-4 py-2">
						<% if surgeon_location.name && surgeon_location.name != "" %>
							<%= surgeon_location.name %>
						<% end %>
						<br/>
						<% if surgeon_location.address_1 && surgeon_location.address_1 != "" %>
							<%= surgeon_location.address_1 %>
						<% end %>
						<br />
						<% if surgeon_location.state != "" && surgeon_location.city != "" && surgeon_location.zip != "" %>
							<%= surgeon_location.city %>, <%= surgeon_location.state %>, <%= surgeon_location.zip %>
						<% elsif surgeon_location.state = "" %>
							<%= surgeon_location.city %>, <%= surgeon_location.zip %>
						<% elsif surgeon_location.city = "" %> 
							<%= surgeon_location.state %>, <%= surgeon_location.zip %>
						<% elsif surgeon_location.zip = "" %> 
							<%= surgeon_location.city %>, <%= surgeon_location.state %>
						<% end %>
						<br />
						<% if surgeon_location.phone_number && surgeon_location.phone_number != "" %>
							Phone: <%= surgeon_location.phone_number %>
						<% end %>
					</td>
					<td class="border px-4 py-2">
						<%= status_mapping[surgeon_location.status] %>
					</td>
					<% if current_user && (current_user.admin? || (current_user.manager? && current_user.id == surgeon_location.user_id)) %>
						<td class="border px-4 py-4" style="min-width: 210px;">
							<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-edit"></i></span>'.html_safe, edit_surgeon_path(surgeon.id), class: "my-2 py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: "Edit Surgeon" %>

							<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-trash"></i></span>'.html_safe, surgeon_path(surgeon.id), method: :delete, data: { confirm: "Are you sure?" }, class: "my-2 py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: "Delete Surgeon" %>

							<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-download"></i>'.html_safe, generate_report_path(surgeon_id: surgeon.id, format: :pdf), class: "my-2 py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: "Download Report" %>
						</td>
					<% else %>
						<td class="border px-4 py-2">-</td>
					<% end %>
				</tr>
			<% end %>
	</tbody>
	</table>
	<div class="digg_pagination">
	    <div class="page_info">
	      <%= page_entries_info @surgeons %>
	    </div>
	    <%= will_paginate @surgeons, :container => false %>
    </div>
  <% else %>
  	<p class="pad-10">There are are no surgeons!</p>
  <% end %>

app/views/surgeons/new.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">New Surgeon - Create a new surgeon</h3>
</div>

<div class="flex flex-wrap">
	<%= render 'form' %>
</div>

app/views/surgeons/show.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Surgeon Details:</h3>
</div>
<div style="margin:3em;">
<% @location = @surgeon.location %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Name: <%= @surgeon.full_name %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Professional Suffix: <%= @surgeon.suffix %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Email: <%= @surgeon.email %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Procedure Types: <%= @surgeon.procedure_types_array %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Website:  <%= @surgeon.url %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Phone: <%= @surgeon.phone %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    	Status: <%= @surgeon.status %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
	Address:  <%= "#{@location.address_1}, #{@location.address_2}, #{@location.city}, #{@location.state}, #{@location.zip}, #{@location.country}" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
		Location Phone: <%= "#{@location.phone_number}" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
		Location Fax: <%= "#{@location.fax_number}" %>
    </div>
</div>
<br/>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-2/3">
		<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><span class="fl">Edit</span></span>'.html_safe, edit_surgeon_path(@surgeon.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
    </div>
</div>
</div>