config/routes.rb
Rails.application.routes.draw do
   devise_for :users, skip: [:registrations]
   as :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      get 'dashboard' => 'devise/sessions#new'
  end
  resources :users, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :surgeons
  resources :locations do
    resources :surgeons
  end
  resources :searches
  resources :admin_analytics
  # root 'surgeons#index'

  # routes to set location/surgeon to "live/public"
  get 'set_surgeon_status', to: 'surgeons#set_status'
  get 'set_location_status', to: 'locations#set_status'
  # root page
  root 'admin_analytics#dashboard'

  # surgeon locator page - internal
  get 'search_surgeons', to: 'searches#surgeon_locator'
  #display the surgeons when details are submitted in surgeon locator page
  post '/map_the_surgeons',  to: 'searches#map_the_surgeons'

  #track the website click in surgeon locator page
  get '/track_the_clicks', to: 'searches#track_the_clicks'

  #export db as .xls for admin
  get '/export_db', to: 'admin_analytics#export_db'

  #admin analytics - search results
  get '/search_results', to: 'admin_analytics#search_results'
  #admin analytics - download pdf report for surgeon
  get 'generate_report', to: 'admin_analytics#generate_report'
  #admin analytics - show heat map in pdfs
  get '/show_heat_map', to: 'admin_analytics#show_heat_map'
  #admin analytics - download client reports
  get '/client_reports', to: 'admin_analytics#client_reports'

  #list of all users - admin/location manager
  get '/users', to: 'admin_analytics#users_list'
  get '/reactive_users', to: 'admin_analytics#reactive_users'
  get 'update_reactive_user/:id', controller: 'admin_analytics', action: :update_reactive_user, as: :update_reactive_user

  #track the phone number clicks in surgeon locator page
   post '/track_the_phone', to: 'searches#track_the_phone'

  #external - surgeon locator
  get 'surgeon_finder', to: 'searches#surgeon_finder'
  get 'dashboard', to: 'admin_analytics#dashboard'

  #activate surgeons/locations
  get 'activate_surgeons', to: 'admin_analytics#activate_surgeons'
  get 'publish_surgeon', to: 'admin_analytics#publish_surgeon'
  get 'activate_locations', to: 'admin_analytics#activate_locations'
  get 'publish_location', to: 'admin_analytics#publish_location'
end

app/controllers/admin_analytics_controller.rb
class AdminAnalyticsController < ApplicationController
  skip_before_action :authenticate_user!, :except => [:index, :search_results]

  def index
    if params[:search]
      @searches = Search.order("id DESC").search(params[:search]).paginate(page: params[:page], per_page: 30)
    else
      @searches = Search.group(:zip).count.sort_by { |k, v| v }.reverse
    end
  end

  def search_results
    @search = Search.find(params[:id])
    @search_results = SearchResult.where(search_id: params[:id]).paginate(page: params[:page], per_page: 30)
  end

  # Admin generates report for each dr
  def generate_report
    Geokit::Geocoders::GoogleGeocoder.api_key = Rails.application.secrets.google_maps_api_key
    @surgeon = Surgeon.find(params[:surgeon_id])
    location = Location.find(@surgeon.location_id)
    search50 = Search.near([location.latitude, location.longitude], 50, order: :id)
    search25 = Search.near([location.latitude, location.longitude], 25, order: :id)
    search50_ids = search50.pluck(:id).to_s.gsub!(/[\[\]]/, "") rescue []
    search25_ids = search25.pluck(:id).to_s.gsub!(/[\[\]]/, "") rescue []
    @results_50 = Search.where("id = ANY (?) AND id <> ALL (?)", "{#{search50_ids}}", "{#{search25_ids}}").group(:zip).limit(10).count(:zip)
    @results_25 = Search.where("id = ANY (?)", "{#{search25_ids}}").group(:zip).limit(10).count(:zip)
    # @results_25 = SearchResult.joins(:search).where("searches.search_radius = 25 and search_results.surgeon_id = #{params[:surgeon_id]}").group(:zip).limit(10).count(:surgeon_id)

    # @results_50 = SearchResult.joins(:search).where("searches.search_radius = 50 and search_results.surgeon_id = #{params[:surgeon_id]}").group(:zip).limit(10).count(:surgeon_id)

    @procedure_types = @surgeon.procedure_types_array if @surgeon.procedure_types_array
    @total_surgeons = Surgeon.all.count

    @surgeons_cervical_fusion = Surgeon.where("'Cervical Fusion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cervical_motion = Surgeon.where("'Cervical Motion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_lumbar_motion = Surgeon.where("'Lumbar Motion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_lumbar_fusion = Surgeon.where("'Lumbar Fusion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cc_cervical = Surgeon.where("'Comprehensive Care Cervical' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cc_lumbar = Surgeon.where("'Comprehensive Care Lumbar' = ANY (surgeons.procedure_types_array)").count

    # @total_search_count = Search.where("id = ANY (?)", "{#{search50_ids}}").count
    @cervical_fusion_count = Search.where("id = ANY (?) AND 'Cervical Fusion' = ANY (procedure_type)", "{#{search50_ids}}").count
    @cervical_motion_count = Search.where("id = ANY (?) AND 'Cervical Motion' = ANY (procedure_type)", "{#{search50_ids}}").count
    @lumbar_motion_count = Search.where("id = ANY (?) AND 'Lumbar Motion' = ANY (procedure_type)", "{#{search50_ids}}").count
    @lumbar_fusion_count = Search.where("id = ANY (?) AND 'Lumbar Fusion' = ANY (procedure_type)", "{#{search50_ids}}").count
    @cc_fusion_count = Search.where("id = ANY (?) AND 'Comprehensive Care Cervical' = ANY (procedure_type)", "{#{search50_ids}}").count
    @cc_motion_count = Search.where("id = ANY (?) AND 'Comprehensive Care Lumbar' = ANY (procedure_type)", "{#{search50_ids}}").count

    @total_search_count = @cervical_fusion_count + @cervical_motion_count + @lumbar_motion_count + @lumbar_fusion_count + @cc_fusion_count +  @cc_motion_count

    @total_clicks = @surgeon.links.where(link_type: "website").count
    @phone_calls = @surgeon.links.where(link_type: "phone").count

    #grover
    respond_to do |format|
      format.html
      format.pdf do
        grover = Grover.new(root_url + "generate_report?surgeon_id=#{params[:surgeon_id]}", format: "A4", timeout: 0)
        pdf = grover.to_pdf
        File.open("dr_report.pdf", "wb+", encoding: "ascii-8bit") do |f|
          f.write(pdf)
        end
        send_data File.open("dr_report.pdf", "rb").read, type: "application/pdf", filename: "Report for Dr. #{@surgeon.full_name}.pdf" #, disposition: "inline"
      end
    end
  end

  #To show heat map
  def show_heat_map
    Geokit::Geocoders::GoogleGeocoder.api_key = Rails.application.secrets.google_maps_api_key
    if params[:surgeon_id] && params[:surgeon_id] != ""
      surgeon = Surgeon.find(params[:surgeon_id])
      location = Location.find(surgeon.location_id)
      search50 = Search.near([location.latitude, location.longitude], 50, order: :id)
      search50_ids = search50.pluck(:id).to_s.gsub!(/[\[\]]/, "") rescue []
      results_50 = Search.where("id = ANY (?)", "{#{search50_ids}}").select("latitude, longitude")
      center = { "latitude" => location.latitude, "longitude" => location.longitude }
    else
      #for the client specific reports
      results_50 = Search.select("latitude, longitude")
      center = { "latitude" => "37.00", "longitude" => "-118.00" }
    end
    if results_50
      render json: { locations: results_50, center: center }, status: :ok
    else
      render json: { errors: "Locations not found." }, status: :unprocessable_entity
    end
  end

  # Client specific reports
  def client_reports
    @zip_codes = Search.all.group(:zip).select("count(zip) as count_zip, zip as searched_zip").limit(10)
    @searched_surgeons = Link.joins(surgeon: :location).group("links.surgeon_id, locations.phone_number, locations.zip, surgeons.url, surgeons.full_name").select("count(surgeon_id), surgeon_id, surgeons.full_name, locations.phone_number, locations.zip, surgeons.url").order("count DESC").limit(5)

    @total_surgeons = Surgeon.all.count

    @surgeons_cervical_fusion = Surgeon.where("'Cervical Fusion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cervical_motion = Surgeon.where("'Cervical Motion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_lumbar_motion = Surgeon.where("'Lumbar Motion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_lumbar_fusion = Surgeon.where("'Lumbar Fusion' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cc_cervical = Surgeon.where("'Comprehensive Care Cervical' = ANY (surgeons.procedure_types_array)").count
    @surgeons_cc_lumbar = Surgeon.where("'Comprehensive Care Lumbar' = ANY (surgeons.procedure_types_array)").count

    # @total_search_count = Search.count
    @cervical_fusion_count = Search.where("'Cervical Fusion' = ANY (procedure_type)").count
    @cervical_motion_count = Search.where("'Cervical Motion' = ANY (procedure_type)").count
    @lumbar_motion_count = Search.where("'Lumbar Motion' = ANY (procedure_type)").count
    @lumbar_fusion_count = Search.where("'Lumbar Fusion' = ANY (procedure_type)").count
    @cc_fusion_count = Search.where("'Comprehensive Care Cervical' = ANY (procedure_type)").count
    @cc_motion_count = Search.where("'Comprehensive Care Lumbar' = ANY (procedure_type)").count
    @total_search_count =  @cervical_fusion_count + @cervical_motion_count + @lumbar_motion_count + @lumbar_fusion_count + @cc_fusion_count + @cc_motion_count

    logger.info "total_surgeons---#{@total_surgeons.size}---#{@surgeons_cervical_fusion.size}"

    #grover
    respond_to do |format|
      format.html
      format.pdf do
        grover = Grover.new(root_url + "client_reports", format: "A4", timeout: 0, cache: false)
        pdf = grover.to_pdf
        File.open("client_report.pdf", "wb+", encoding: "ascii-8bit") do |f|
          f.write(pdf)
        end
        #File.open(Rails.root.join('client_report.pdf'),'wb', 0644, encoding: 'utf-8') { |f| f.write(pdf)}
        send_data File.open("client_report.pdf", "rb").read, type: "application/pdf", filename: "Results.pdf" #, disposition: "inline"
      end
    end
  end

  #To export db
  def export_db
    @users = User.all
    @locations = Location.all
    @surgeons = Surgeon.all
    @searches = Search.all
    @search_results = SearchResult.all
    @links = Link.all

    respond_to do |format|
      format.html
      format.xlsx do
        response.headers[
          "Content-Disposition"
        ] = "attachment; filename=Locatorapp_development.xlsx"
      end
    end
  end

  #Dashboard - if admin logged in - show dashboard
  def dashboard
    if user_signed_in? && current_user.manager? #managers should see surgeons in their location
      redirect_to surgeons_path(:user_id => current_user.id)
    elsif !user_signed_in? #guest users should see search surgeons
      redirect_to search_surgeons_path
    end
  end

  #list of users
  def users_list
    @users = User.where("deleted_at is NULL").order("id DESC").search(params[:search]).paginate(page: params[:page], per_page: 30)
  end

  def reactive_users
    @users = User.where.not("deleted_at is NULL").order("id DESC").search(params[:search]).paginate(page: params[:page], per_page: 30)
  end

  def update_reactive_user
    @user = User.find_by(id: params[:id])
    @user.update(deleted_at: nil)
    redirect_to reactive_users_path
  end

  #activate surgeons
  def activate_surgeons
    @surgeons = Surgeon.where("status = ?", "private").order("id DESC").search(params[:search]).paginate(page: params[:page], per_page: 30)
  end

  #make the surgeon status from private to publish
  def publish_surgeon
    @surgeon = Surgeon.find(params[:id])
    @surgeon.update_column(:status, "publish")
    flash[:notice] = "Surgeon has been successfully made live. You can now verify and edit the surgeon specialities."
    redirect_to edit_surgeon_path(params[:id])
  end

  #activate locations
  def activate_locations
    @locations = Location.where("status = ?", "private").order("id DESC").search(params[:search]).paginate(page: params[:page], per_page: 30)
  end

  #make the location status from private to publish
  def publish_location
    @location = Location.find(params[:id])
    @location.update_column(:status, "publish")

app/views/admin_analytics/activate_locations.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Activate - Locations added by location managers.</h3>
</div>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<%= form_tag activate_locations_path, method: :get do %>
<% if params[:search] && params[:search] != "" %>
<% @search_val = params[:search] %>
<% else %>
<% @search_val = "" %>
<% end %>
<%= text_field_tag :search, @search_val, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
<%= submit_tag 'Search', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
<% end %>
<% if @locations && @locations.length > 0 %>
<table class="table-fixed">
    <thead>
        <tr>
            <th class="w-1/2 px-4 py-2">
                Name
            </th>
			<th class="w-1/2 px-4 py-2">
                Address
            </th>
			<th class="w-1/2 px-4 py-2">
            </th>
        </tr>
    </thead>
    <tbody>
        <% @locations.each do |result| %>
        <tr>
            <td class="border px-4 py-2">
                <%= result.name %>
            </td>
			<td class="border px-4 py-2">
                <%= result.address_1 %>,<%= result.address_2 %>, <%= result.city %>, <%= result.state %>
            </td>
			<td class="border px-4 py-2">
				<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><span class="fl">Activate</span></span>'.html_safe, publish_location_path(:id => result.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
			</td>
        </tr>
        <% end %>
    </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
        <%= page_entries_info @locations %>
    </div>
    <%= will_paginate @locations, :container => false %>
</div>
<% else %>
<p>
    No Results!
</p>
<% end %>

app/views/admin_analytics/activate_surgeons.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Activate - Surgeons added by location managers.</h3>
</div>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<%= form_tag activate_surgeons_path, method: :get do %>
<% if params[:search] && params[:search] != "" %>
<% @search_val = params[:search] %>
<% else %>
<% @search_val = "" %>
<% end %>
<%= text_field_tag :search, @search_val, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
<%= submit_tag 'Search', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
<% end %>
<% if @surgeons && @surgeons.length > 0 %>
<table class="table-fixed">
    <thead>
        <tr>
            <th class="w-1/2 px-4 py-2">
                Name
            </th>
			<th class="w-1/2 px-4 py-2">
                Email
            </th>
			<th class="w-1/2 px-4 py-2">
            </th>
        </tr>
    </thead>
    <tbody>
        <% @surgeons.each do |result| %>
        <tr>
        	
            <td class="border px-4 py-2">
				<%= link_to "<span class='text-black underline'>#{result.full_name}, #{result.suffix}</span>".html_safe, surgeon_path(result.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
            </td>
			<td class="border px-4 py-2">
                <%= result.email %>
            </td>
			<td class="border px-4 py-2">
				<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><span class="fl">Activate</span></span>'.html_safe, publish_surgeon_path(:id => result.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
			</td>
        </tr>
        <% end %>
    </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
        <%= page_entries_info @surgeons %>
    </div>
    <%= will_paginate @surgeons, :container => false %>
</div>
<% else %>
<p>
    No Results!
</p>
<% end %>

app/views/admin_analytics/dashboard.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Welcome to your dashboard. Please click on any menu.</h3>
</div>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<div class="wid">
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-location-arrow dashbrd-ic"></i><p class="txt-p pad-10">All Locations - Listing of all the locations in the system</p>'.html_safe, locations_path %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-user-md dashbrd-ic"></i><p class="txt-p pad-10">All Surgeons - Listing of all the surgeons in the system</p>'.html_safe, surgeons_path %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="far fa-plus-square dashbrd-ic"></i><p class="txt-p pad-10">New Location - Create a new location</p>'.html_safe, new_location_path %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-search-location dashbrd-ic"></i><p class="txt-p pad-10">Surgeon Locator</p>'.html_safe, search_surgeons_path %>
	</div>
</div>
	<hr />
<div class="wid fl">
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-info-circle dashbrd-ic ht-30"></i><p class="txt-p pad-10">Analytics Data - All searches by Zip codes. Click on Search Results to see the results that appeared</p>'.html_safe, admin_analytics_path %>
	</div>
	<div class="dashbrd-div fl">
        <%= link_to '<i class="fas fa-file-export dashbrd-ic"></i><p class="txt-p pad-10">Export Database - Downloads DB in Excel</p>'.html_safe, export_db_path(format: :xlsx) %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-file-download dashbrd-ic"></i><p class="txt-p pad-10">Client Report - Downloads the client specific report</p>'.html_safe, client_reports_path(format: :pdf) %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-user-plus dashbrd-ic"></i><p class="txt-p pad-10">Invite User - Invite Admin/Location Managers to the system</p>'.html_safe, new_user_invitation_path %>
	</div>
	<div class="wid">
	</div>
</div>
<div class="wid fl">
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-users dashbrd-ic"></i><p class="txt-p pad-10">All Users - Listing of all the users in the system</p>'.html_safe, users_path %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-unlock dashbrd-ic ht-30" ></i><p class="txt-p pad-10">Publish Surgeons - Activate the surgeons added by Location Managers.</p>'.html_safe, activate_surgeons_path %>
	</div>
	<div class="dashbrd-div fl">
		<%= link_to '<i class="fas fa-unlock dashbrd-ic ht-30"></i><p class="txt-p pad-10">Publish Locations - Activate the locations added by Location Managers.</p>'.html_safe, activate_locations_path %>
	</div>
	<div class="wid">
	</div>
</div>

app/views/admin_analytics/index.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Analytics Data - All searches by Zip codes. Click on Search Results to see the results that appeared.</h3>
</div>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<%= form_tag admin_analytics_path, method: :get do %>
  <% if params[:search] && params[:search] != "" %>
  	<% @search_val = params[:search] %>
  <% else %>
  	<% @search_val = "" %>
  <% end %>
  <%= text_field_tag :search, @search_val, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
  <%= submit_tag 'Search', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
<% end %>
<% if params[:search].present? &&  @searches.length > 0%>
  <div class='ml-2'>
    <h2 class='font-bold'>Radius</h2>
    <% @searches.group(:search_radius).count.each do |radius, count|  %>
      <%= "#{radius} miles: #{count}" %>
    <% end %>
    <h2 class='font-bold mt-4'>Procedure Types</h2>
    <% @searches.group(:procedure_types).count.each do |procedure_type, count|  %>
      <%= "#{procedure_type}: #{count}" %>
    <% end %>
    <h2 class='font-bold mt-4'>Area of Discomfort</h2>
    <% @searches.group(:area_of_discomfort).count.each do |area_of_discomfort, count|  %>
      <%= "#{area_of_discomfort}: #{count}" %>
    <% end %>
  </div>
<table class="table-fixed">
    <thead>
        <tr>
            <th class="w-1/2 px-4 py-2">
                Zip Code
            </th>
            <th class="w-1/2 px-4 py-2">
                Search Radius
            </th>
            <th class="w-1/2 px-4 py-2">
                Procedure Types
            </th>
            <th class="w-1/2 px-4 py-2">
                Area of Discomfort
            </th>
            <th class="w-1/2 px-4 py-2">
            	Results
            </th>
        </tr>
    </thead>
    <tbody>
        <% @searches.each do |result| %>
        <tr>
            <td class="border px-4 py-2">
                <%= result.zip %>
            </td>
            <td class="border px-4 py-2">
                <%= result.search_radius %>
            </td>
            <td class="border px-4 py-2">
                <%= result.procedure_types %>
            </td>
            <td class="border px-4 py-2">
                <%= result.area_of_discomfort %>
            </td>
            <td class="border px-4 py-2">
				<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><span class="fl">Search Results</span></span>'.html_safe, search_results_path(id: result.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
			</td>
        </tr>
        <% end %>
    </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
        <%= page_entries_info @searches %>
    </div>
    <%= will_paginate @searches, :container => false %>
</div>
<% else %>
  <div class='ml-4'>
    <h2 class='font-bold text-2xl'>Results by Zip</h2>
    <% @searches.each do |search| %>
      <span class='font-bold text-blue-400 text-xl'><%= link_to "#{search[0]}", admin_analytics_path(:search => search[0]) %></span>
      <span class='text-xl'><%= ": #{search[1]} searches" %></span>
      <br />
    <% end %>
  </div>
<% end %>

app/views/admin_analytics/search_results.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Search Results for: <%= @search.zip %>, <%= @search.search_radius %> Radius, <%= @search.procedure_types %> and User discomfort - <%= @search.area_of_discomfort %> </h3>
</div>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<% if @search_results && @search_results.length > 0 %>
<table class="table-fixed">
    <thead>
        <tr>
            <th class="w-1/2 px-4 py-2">
                Surgeon Name, Professional_Suffix
            </th>
			<th class="w-1/2 px-4 py-2">
            	Website clicks?
            </th>
			<th class="w-1/2 px-4 py-2">
            	Phone clicks?
            </th>
			<th class="w-1/2 px-4 py-2">
            	Generate Report
            </th>
        </tr>
    </thead>
    <tbody>
        <% @search_results.each do |result| %>
		<% surgeon = result.surgeon %>
		<% location = surgeon.location %>
		<% search = result.search %>
		<% website_clicks = Link.where(search_id: search.id, surgeon_id: surgeon.id, link_type: "website") %>
		<% phone_clicks = Link.where(search_id: search.id, surgeon_id: surgeon.id, link_type: "phone") %>
		<tr>
            <td class="border px-4 py-2">
				<%= link_to "<span class='text-black underline'>#{surgeon.full_name}, #{surgeon.suffix}</span>".html_safe, surgeon_path(surgeon.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
            </td>
			<td class="border px-4 py-2">
				<% if ( website_clicks && website_clicks.length > 0 ) %> <%= website_clicks.length %> <% else %> 0 <% end %>
            </td>
			<td class="border px-4 py-2">
				<% if ( phone_clicks && phone_clicks.length > 0 ) %> <%= phone_clicks.length %> <% else %> 0 <% end %>
            </td>
            <td class="border px-4 py-2">
				<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><svg class="fill-current w-4 h-svg-dld mr-2 fl" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg><span class="fl">Download Report</span></span>'.html_safe, generate_report_path(surgeon_id: surgeon.id, format: :pdf), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white"  %>
			</td>
				
        </tr>
        <% end %>
    </tbody>
</table>
<div class="digg_pagination">
    <div class="page_info">
        <%= page_entries_info @search_results %>
    </div>
    <%= will_paginate @search_results, :container => false %>
</div>
<% else %>
<p>
    There are are no user searches done yet!
</p>
<% end %>