config/routes.rb
Rails.application.routes.draw do
   devise_for :users, skip: [:registrations]
   as :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      get 'dashboard' => 'devise/sessions#new'
  end
  resources :users, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :surgeons
  resources :locations do
    resources :surgeons
  end
  resources :searches
  resources :admin_analytics
  # root 'surgeons#index'

  # routes to set location/surgeon to "live/public"
  get 'set_surgeon_status', to: 'surgeons#set_status'
  get 'set_location_status', to: 'locations#set_status'
  # root page
  root 'admin_analytics#dashboard'

  # surgeon locator page - internal
  get 'search_surgeons', to: 'searches#surgeon_locator'
  #display the surgeons when details are submitted in surgeon locator page
  post '/map_the_surgeons',  to: 'searches#map_the_surgeons'

  #track the website click in surgeon locator page
  get '/track_the_clicks', to: 'searches#track_the_clicks'

  #export db as .xls for admin
  get '/export_db', to: 'admin_analytics#export_db'

  #admin analytics - search results
  get '/search_results', to: 'admin_analytics#search_results'
  #admin analytics - download pdf report for surgeon
  get 'generate_report', to: 'admin_analytics#generate_report'
  #admin analytics - show heat map in pdfs
  get '/show_heat_map', to: 'admin_analytics#show_heat_map'
  #admin analytics - download client reports
  get '/client_reports', to: 'admin_analytics#client_reports'

  #list of all users - admin/location manager
  get '/users', to: 'admin_analytics#users_list'
  get '/reactive_users', to: 'admin_analytics#reactive_users'
  get 'update_reactive_user/:id', controller: 'admin_analytics', action: :update_reactive_user, as: :update_reactive_user

  #track the phone number clicks in surgeon locator page
   post '/track_the_phone', to: 'searches#track_the_phone'

  #external - surgeon locator
  get 'surgeon_finder', to: 'searches#surgeon_finder'
  get 'dashboard', to: 'admin_analytics#dashboard'

  #activate surgeons/locations
  get 'activate_surgeons', to: 'admin_analytics#activate_surgeons'
  get 'publish_surgeon', to: 'admin_analytics#publish_surgeon'
  get 'activate_locations', to: 'admin_analytics#activate_locations'
  get 'publish_location', to: 'admin_analytics#publish_location'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :surgeons, dependent: :destroy
  validates_presence_of :address_1, :city, :state, :country
  #  validates_presence_of :name, :address_1, :address_2, :city, :state, :zip, :country, :fax_number, :phone_number

  STATUS = %w[private publish]
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? and (obj.address_1_changed? || obj.city_changed? || obj.state_changed? || obj.country_changed?) }

  def address
    [address_1, city, state, country].compact.join(", ")
  end

  def self.search(search)
    locations = all # for not existing search params
    locations = locations.where("LOWER(name) like LOWER('%#{search}%') OR LOWER(website) like LOWER('%#{search}%') OR LOWER(address_1) like LOWER('%#{search}%') OR LOWER(address_2) like LOWER('%#{search}%') OR LOWER(city) like LOWER('%#{search}%') OR LOWER(state) like LOWER('%#{search}%') OR zip like '%#{search}%' OR phone_number like '%#{search}%' OR fax_number like '%#{search}%'") if search
    locations
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 30) if current_user.admin?
    if current_user && current_user.manager?
      @my_location = Location.find_by_user_id(current_user.id)
      @locations = current_user.locations.paginate(page: params[:page], per_page: 30)
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @my_location = Location.find_by_user_id(current_user.id) if current_user && current_user.manager?
    unless @my_location
      @location = Location.new
    else
      flash[:notice] = "You are the client manager of a location, so you can't add more location(s)."
      redirect_to locations_path
    end
  end

  #save/create location and then save the surgeon details
  def create
    @location = Location.new(params_location)
    @location.user_id = current_user.id
    #    @location.status = "publish" if current_user && current_user.admin?
    if @location.save
      full_location = @location.city + ", "+ CS.states(:us)[@location.state.to_sym] + ", " +@location.country
      latitude, longitude = Geocoder.search(full_location)&.first&.coordinates
      @location.update_attributes(longitude: longitude, latitude: latitude)
      
      if current_user && current_user.manager?
        @admins = User.where("role = ? and deleted_at is NULL", "admin")
        @admins.each do |admin|
          NotificationMailer.added_location_email(@location, admin.email).deliver_now
        end
        flash[:notice] = "Location has been successfully created. Admin will verify and approve the location."
      elsif current_user && current_user.admin?
        flash[:notice] = "Location has been successfully created."
      end
      redirect_to locations_path
    else
      render "new"
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    # Geokit::Geocoders::GoogleGeocoder.api_key = Rails.application.secrets.google_maps_api_key
    # location = Location.last.city + ", "+ CS.states(:us)[Location.last.state.to_sym] + ", " + Location.last.country
    # coords = MultiGeocoder.geocode(location)

    @location = Location.find(params[:id])
    if @location.update(params_location)
      full_location = @location.city + ", "+ CS.states(:us)[@location.state.to_sym] + ", " +@location.country
      latitude, longitude = Geocoder.search(full_location)&.first&.coordinates
      @location.update_attributes(longitude: longitude, latitude: latitude)
      flash[:notice] = "Location has been successfully updated."
      redirect_to locations_path
    else
      render "edit"
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    flash[:notice] = "Location has been successfully deleted."
    redirect_to locations_path
  end

  #make the location status from private to publish
  #  def set_status
  #    if current_user && current_user.admin?
  #      @location = Location.find(params[:id])
  #      @location.update_column(:status, "publish")
  #      flash[:notice] = "Location has been successfully made live."
  #    else
  #      flash[:notice] = "Sorry. Only admin has the rights to make a location live."
  #    end
  #    redirect_to locations_path
  #  end

  private

  def params_location
    params.require(:location).permit(:user_id, :name, :website, :address_1, :address_2, :city, :state, :zip, :country, :fax_number, :phone_number, :longitude, :latitude, :status)
  end
end

app/views/locations/_form.html.erb
<%= form_with model: @location, local: true, :class => 'w-full max-w-sm' do |f| %>
<% if flash[:notice] %>
<div class="notice">
    <%= flash[:notice] %>
</div>
<% end %>
<div class="">
    <% if @location.errors.any? %>
    <div id="error_explanation" style="color: red">
        <h2><% @count = @location.errors.count %>
            <%= pluralize(@count, "error") %>prohibited
            this location from being saved:</h2>
        <ul>
            <% @location.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :name, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :name, autofocus: true, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :website, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :website, autofocus: true, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :address_1,  :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :address_1, required: true, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :address_2, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :address_2, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :city, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :city,  required: true, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :state,  :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <select id="location_state" name="location[state]" required="true" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
            <option value="">Select Your State</option>
            <% CS.states(:us).each do |key, value| %>
            <% if @location && @location.state.to_s == key.to_s %>
            <option selected value="<%= key %>"><%= value %></option>
            <% else %>
            <option value="<%= key %>"><%= value %></option>
            <% end %>
            <% end %>
        </select>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :zip, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :zip, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<!-- <div class="md:flex md:items-center mb-6">
<div class="md:w-1/3">
<%= f.label :country, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
<br>
</div>
<div class="md:w-2/3">
<%= f.text_field :country, :value => "USA", :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
</div>
</div>-->
<%= f.hidden_field :country, :value => "USA", :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :phone_number, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :phone_number, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :fax_number, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br>
    </div>
    <div class="md:w-2/3">
        <%= f.text_field :fax_number, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
</div>
<% if current_user && current_user.admin? %>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
        <%= f.label :status, :class => "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
        <br/>
    </div>
    <div class="md:w-2/3">
        <%= f.collection_select :status, Location::STATUS, :to_s, :titleize, {selected: @location.status}, {class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"} %>
    </div>
</div>
<% end %>
<br/>
<div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
    </div>
    <div class="md:w-2/3">
        <%= f.submit 'Save', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
</div>
<% end %>

app/views/locations/edit.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">Edit Location</h3>
</div>

<div class="flex flex-wrap">
	<%= render 'form' %>
</div>

app/views/locations/index.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">All Locations - Listing of all the locations in the system</h3>
	<% if @my_location && @my_location != "" %>
		<h2 class="font-bold pl-2">My location:
			<% if @my_location.name && @my_location.name != "" %><%= @my_location.name %><% end %>
			<% if @my_location.address_1 && @my_location.address_1 != "" %>, <%= @my_location.address_1 %><% end %>
			<% if @my_location.address_2 && @my_location.address_2 != "" %>, <%= @my_location.address_2 %><% end %>
			<% if @my_location.city && @my_location.city != "" %>, <%= @my_location.city %><% end %>
			<% if @my_location.state && @my_location.state != "" %>, <%= @my_location.state %><% end %>
			<% if @my_location.zip && @my_location.zip != "" %>-<%= @my_location.zip %><% end %>
		</h2>
	<% end %>
</div>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= form_tag locations_path, method: :get do %>
  <% if params[:search] && params[:search] != "" %>
  	<% @search_val = params[:search] %>
  <% else %>
  	<% @search_val = "" %>
  <% end %>
  <%= text_field_tag :search, @search_val, :class => "bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
  <%= submit_tag 'Search', :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
<% end %>
<% if @locations && @locations.length > 0 %>
	<table class="table-fixed" width="100%">
		<thead>
		<tr>
			<th class="w-1/2 px-4 py-2">Name</th>
			<th class="w-1/2 px-4 py-2">Website</th>
			<th class="w-1/2 px-4 py-2">Address</th>
			<th class="w-1/2 px-4 py-2">Zip</th>
			<th class="w-1/2 px-4 py-2">City, State</th>
			<th class="w-1/2 px-4 py-2">Phone</th>
			<th class="w-1/2 px-4 py-2">Fax</th>
			<th class="w-1/2 px-4 py-2">Status</th>
      		<th class="w-1/2 px-4 py-2"></th>
		</tr>
		</thead>
		<tbody>
		<%status_mapping = {'publish' => 'Published', 'private' => 'Private'}%>
		<% @locations.each do |location| %>
			<tr>
				<td class="border px-4 py-2"><%= location.name %></td>
				<td class="border px-4 py-2" style="width: 40%; word-break: break-all;"><%= location.website %></td>
				<td class="border px-4 py-2"><%= location.address_1 %><br /><%= location.address_2 %></td>
				<td class="border px-4 py-2"><%= location.zip.present? ? location.zip : '' %></td>
				<td class="border px-4 py-2"><%= location.city %>, <%= location.state %></td>
				<td class="border px-4 py-2"><%= location.phone_number %></td>
				<td class="border px-4 py-2"><%= location.fax_number %></td>
				<td class="border px-4 py-2"><%= status_mapping[location.status] %></td>
				<% if current_user && (current_user.admin? || ( current_user.manager? && current_user.id == location.user_id)) %>
					<td class="border px-4 py-4" style="display:flex;">
						<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-edit"></i></span>'.html_safe, edit_location_path(location.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: 'Edit Location'  %>
						<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-trash"></i></span>'.html_safe, location_path(location.id), method: :delete, data: {confirm: "Are you sure? If you proceed, all Surgeons in this location will also be deleted."}, class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: 'Delete Location'  %>
						<%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-plus"></i></span>'.html_safe, new_surgeon_path(:location_id => location.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: 'Add Surgeon'  %>
		            <%= link_to '<span class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded inline-flex items-center"><i class="fas fa-list"></i></span>'.html_safe, location_surgeons_path(:location_id => location.id), class: "block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white", title: 'Surgeons'  %>
		          </td>
				<% else %>
					<td class="border px-4 py-2">-</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
	</table>
	<div class="digg_pagination">
	    <div class="page_info">
	      <%= page_entries_info @locations %>
	    </div>
	    <%= will_paginate @locations, :container => false %>
    </div>
  <% else %>
  	<p class="pad-10">There are are no locations!</p>
  <% end %>

app/views/locations/new.html.erb
<div class="bg-blue-800 p-2 shadow text-xl text-white">
    <h3 class="font-bold pl-2">New Location - Create a new location</h3>
</div>

<div class="flex flex-wrap">
	<%= render 'form' %>
</div>

app/views/locations/show.html.erb
<br />
<%= @location.name %>
<%= @location.address_1 %>
<%= @location.address_2 %>
<%= @location.city %>
<%= @location.state %>
<%= @location.zip %>
<%= @location.country %>
<%= @location.phone_number %>
<%= @location.fax_number %>
<%= link_to "Edit me", edit_location_path(@location.id) %>